#! /bin/zsh

alias webshop_log="docker logs -f $(docker-compose -f $HOME/workspace/trydent/docker-compose.yml ps -q webshop)"
alias clear_ram="sudo sh -c 'free -h; echo 3 > /proc/sys/vm/drop_caches; swapoff -a; swapon -a; free -h'"

# CloudSuite
CSCONFIG="$HOME/workspace/trydent/docker-compose.yml"
CSACONFIG="$HOME/workspace/cloudsuite-app/docker-compose.yml"
alias cs_redis="docker-compose -f $CSCONFIG exec redis redis-cli"
alias cs_app="docker-compose -f $CSACONFIG down && xhost +local:docker; docker-compose -f $CSACONFIG up -d"
