- hosts: localhost
  pre_tasks:
    - name: Install base dependencies
      roles:
        - base
  post_tasks:
    - name: Install the rest of the dependencies
      roles:
        - git
        - autorandr
        - bcompare
