- name: Install autorandr
  become: yes
  package:
    name:
      - autorandr
    state: present

- name: Copy autorandr config directories
  copy:
    src: "{{ ansible_env.PWD }}/roles/user/files/.config/autorandr/"
    dest: "{{ ansible_env.HOME }}/.config/autorandr/"
