- name: Install bspwm dependency
  become: yes
  package:
    name:
      - bspwm
    state: present

- name: Copy bspwm config files
  copy:
    src: "{{ ansible_env.PWD }}/roles/user/files/.config/bspwm/"
    dest: "{{ ansible_env.HOME }}/.config/bspwm/"
