- name: Install autorandr and copy files
  import_tasks: autorandr.yml

- name: Install bspwm and copy files
  import_tasks: bspwm.yml

- name: Install polybar and copy files
  import_tasks: polybar.yml

- name: Install sxhkd and copy files
  import_tasks: sxhkd.yml

- name: Copy X11 files
  import_tasks: X11.yml

- name: Copy User dotfiles
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.aliases", dest: "{{ ansible_env.HOME }}/.aliases" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.vimrc", dest: "{{ ansible_env.HOME }}/.vimrc" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.zprofile", dest: "{{ ansible_env.HOME }}/.zprofile" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
