- name: Install autorandr and copy files
  import_tasks: autorandr.yml

- name: Install bspwm and copy files
  import_tasks: bspwm.yml

- name: Install dunst and copy files
  import_tasks: dunst.yml

- name: Copy GTK 3.0 files
  import_tasks: gtk-3.0.yml

- name: Install kitty and copy files
  import_tasks: kitty.yml

- name: Copy ntfd files
  import_tasks: ntfd.yml

- name: Install picom and copy files
  import_tasks: picom.yml

- name: Install polybar and copy files
  import_tasks: polybar.yml

- name: Install rofi and copy files
  import_tasks: rofi.yml

- name: Install sxhkd and copy files
  import_tasks: sxhkd.yml

- name: Copy X11 files
  import_tasks: X11.yml

- name: Copy User dotfiles
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.aliases", dest: "{{ ansible_env.HOME }}/.aliases" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.vimrc", dest: "{{ ansible_env.HOME }}/.vimrc" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.zprofile", dest: "{{ ansible_env.HOME }}/.zprofile" }
    - { src: "{{ ansible_env.PWD }}/roles/user/files/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
