- name: Install polybar dependency
  become: yes
  package:
    name:
      - polybar
    state: present

- name: Copy polybar config files
  copy:
    src: "{{ ansible_env.PWD }}/roles/user/files/.config/polybar/"
    dest: "{{ ansible_env.HOME }}/.config/polybar/"

- name: Change file permission for polybar executables
  file: dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { dest: "{{ ansible_env.HOME }}/.config/polybar/launch.sh", mode: +x }
    - { dest: "{{ ansible_env.HOME }}/.config/polybar/scripts/notifications-clear.sh", mode: +x }
    - { dest: "{{ ansible_env.HOME }}/.config/polybar/scripts/notifications-open-all.sh", mode: +x }
    - { dest: "{{ ansible_env.HOME }}/.config/polybar/scripts/package-updates.sh", mode: +x }
