- name: Install polybar dependency
  become: yes
  package:
    name:
      - polybar
    state: present

- name: Get current user
  command: whoami
  changed_when: false
  become: false
  register: whoami

- name: Copy polybar config files
  become_user: "{{  whoami.stdout }}"
  copy:
    src: "{{ ansible_env.PWD }}/roles/user/files/.config/polybar/"
    dest: "{{ ansible_env.HOME }}/.config/polybar/"
