- name: Install sxhkd dependency
  become: yes
  package:
    name:
      - sxhkd
    state: present

- name: Copy sxhkd config file
  copy:
    src: "{{ ansible_env.PWD }}/roles/user/files/.config/sxhkd/"
    dest: "{{ ansible_env.HOME }}/.config/sxhkd/"
    backup: yes
