#! /bin/zsh

# Global aliases
alias vim="nvim"
alias clear_ram="sudo sh -c 'free -h; echo 3 > /proc/sys/vm/drop_caches; swapoff -a; swapon -a; free -h'"
alias lg="lazygit"
alias update-portainer="$HOME/update-portainer.sh"
alias vpn="sudo openvpn --config .openvpn3/autoload/cloudsuite.ovpn"
alias vpnlocal="sudo openvpn --config .openvpn3/autoload/local.ovpn"
alias vpn3="openvpn3 session-start --config .openvpn3/autoload/cloudsuite.ovpn"
alias vpn3local="sudo openvpn3 session-start --config .openvpn3/autoload/local.ovpn"
alias change-wallpaper="/home/stevendejong/.config/systemd/user/scripts/wallpaper.sh"
alias used-ports="sudo lsof -i -P -n | grep LISTEN"


function bluecon {
    device=$1
    if [[ $device == "headphone" ]]; then
        bluetoothctl connect "70:26:05:88:2E:71"
    fi

    if [[ $device == "airpods" ]]; then
        bluetoothctl connect "60:93:16:3C:D3:B9"
    fi

    if [[ $device == "soundbar" ]]; then
        bluetoothctl connect "D8:E3:A7:D1:36:71"
    fi
}

alias btheadphone="bluecon headphone"
alias btairpods="bluecon airpods"
alias btsoundbar="bluecon soundbar"

function cloudsuite_cli {
   CSCONFIG="$HOME/workspace/trydent/docker-compose.yml"
   CSCONFIG_OVERRIDE="$HOME/workspace/trydent/docker-compose.override.yml"
   CSTESTCONFIG="$HOME/workspace/trydent/docker-compose.tests.yml"
   CSACONFIG="$HOME/workspace/cloudsuite-app/docker-compose.yml"

   POSITIONAL_ARGS=()

   function help {
      echo "
      Usage:
      -l|--log [-c|--container]
      -r|--redis [-c|--command]
      -m|--migrate
      -tr|--trydent
      -t|--test
      -a|--app
      -h|--help
      "
   }

   while [[ $# -gt 0 ]]; do
      case $1 in
         -l|--log)
            case $2 in
               -c|--container)
                  echo "Start logging for ($3)"
                  docker logs -f $(docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE ps -q $3)
                  return
                  ;;
               *)
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE logs -f
                  return
                  ;;
            esac
            return
            ;;
         -r|--redis)
            case $2 in
               -c|--command)
                  echo "Redis cli ($3)"
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec redis redis-cli $3
                  return
                  ;;
               *)
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec redis redis-cli
                  return
                  ;;
            esac
            return
            ;;
         -m|--migrate)
            docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec trytond /srv/trytond/bin/trytond -d fixture --all -v
            return
            ;;
         -a|--app)
            docker-compose -f $CSACONFIG down && xhost +local:docker; docker-compose -f $CSACONFIG up -d
            return
            ;;
         -tr|trydent)
	    docker-compose -f $CSCONFIG ${@:2}
	    return
	    ;;
	 -t|--test)
	    docker-compose -f $CSTESTCONFIG ${@:2}
	    return
	    ;;
         -h|--help)
            help
            return
            ;;
         -*|--*)
            echo "Unknown option $1"
            return
            ;;
         *)
            help
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
      esac
   done
}

alias cs="cloudsuite_cli"
