#! /bin/zsh

# Global aliases
alias clear_ram="sudo sh -c 'free -h; echo 3 > /proc/sys/vm/drop_caches; swapoff -a; swapon -a; free -h'"
alias lg="lazygit"
alias docker-compose="docker compose"


function bluecon {
    if [[ $1 == "headphone" ]]; then
        bluetoothctl connect 70:26:05:88:2E:71
    fi

    if [[ $1 == "airpods" ]]; then
        bluetoothctl connect 60:93:16:3C:D3:B9
    fi
}


function cloudsuite_cli {
   CSCONFIG="$HOME/workspace/trydent/docker-compose.yml"
   CSCONFIG_OVERRIDE="$HOME/workspace/trydent/docker-compose.override.yml"
   CSACONFIG="$HOME/workspace/cloudsuite-app/docker-compose.yml"

   POSITIONAL_ARGS=()

   function help {
      echo "
      Usage:
      -l|--log [-c|--container]
      -r|--redis [-c|--command]
      -m|--migrate
      -a|--app
      -h|--help
      "
   }

   while [[ $# -gt 0 ]]; do
      case $1 in
         -l|--log)
            case $2 in
               -c|--container)
                  echo "Start logging for ($3)"
                  docker logs -f $(docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE ps -q $3)
                  return
                  ;;
               *)
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE logs -f
                  return
                  ;;
            esac
            return
            ;;
         -r|--redis)
            case $2 in
               -c|--command)
                  echo "Redis cli ($3)"
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec redis redis-cli $3
                  return
                  ;;
               *)
                  docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec redis redis-cli
                  return
                  ;;
            esac
            return
            ;;
         -m|--migrate)
            docker-compose -f $CSCONFIG -f $CSCONFIG_OVERRIDE exec trytond /srv/trytond/bin/trytond -d fixture --all -v
            return
            ;;
         -a|--app)
            docker-compose -f $CSACONFIG down && xhost +local:docker; docker-compose -f $CSACONFIG up -d
            return
            ;;
         -h|--help)
            help
            return
            ;;
         -*|--*)
            echo "Unknown option $1"
            return
            ;;
         *)
            help
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
      esac
   done
}

alias cs="cloudsuite_cli"
