#! /bin/sh

BSPWM_CONFIG=$HOME/.config/bspwm
POLYBAR_CONFIG=$HOME/.config/polybar
WALLPAPERS=$HOME/Pictures/wallpapers

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x xfce4-clipman > /dev/null || xfce4-clipman &
pgrep -x slimbookbattery > /dev/null || slimbookbattery &

bspc config pointer_motion_interval 40

source $BSPWM_CONFIG/workspaces.sh
source $BSPWM_CONFIG/rules.sh
source $BSPWM_CONFIG/styling.sh
source $POLYBAR_CONFIG/launch.sh

# Autostart
dex --autostart

# Set wallpaper
sleep 1
RANDOM_WALLPAPER=$(find $WALLPAPERS/* -xtype f | shuf -n 1) &&
	feh --bg-fill "$RANDOM_WALLPAPER"

