xrdb $HOME/.config/X11/xresources

# This rule is needed when no display manager is used (Removed sddm and use startx instead)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

pgrep -x numlockx > /dev/null || numlockx &
pgrep -x picom > /dev/null || picom &
pgrep -x ntfd > /dev/null || ntfd &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x slstatus > /dev/null || slstatus &

# https://www.reddit.com/r/bspwm/comments/kf7077/no_cursor_on_startup_appears_when_opening_a/
xsetroot -cursor_name left_ptr

# Disable trackpad middle mouse click
xinput set-button-map $(xinput list --id-only 'ETPS/2 Elantech Touchpad') 1 1 3 4 5 6 7

# xautolock -time 10 -locker /usr/local/bin/slock &

xset +fp $HOME/.local/share/fonts
xset +fp /usr/share/fonts &
fc-cache -fv
xset fp rehash &

# Hide cursor after x time
unclutter -idle 3 &

exec dwm > $HOME/.logs/dwm.log 2>&1

