# https://gist.github.com/lbrame/1678c00213c2bd069c0a59f8733e0ee6#forwarding-the-journal-to-devtty12

- name: Have boot messages stay on tty1
  become: yes
  script: "{{ ansible_env.PWD }}/roles/tty/files/tty1-boot-message.sh"

- name: Forwarding the journal to /dev/tty12
  become: yes
  script: "{{ ansible_env.PWD }}/roles/tty/files/forward-journald.sh"
