# https://www.pc-freak.net/blog/set-logs-log-physical-console-devtty12-tty12-linux/

- name: Have boot messages stay on tty1
  become: yes
  command: echo "[Service]\nTTYVTDisallocate=no\n" > /etc/systemd/system/getty@tty1.service.d/noclear.conf

- name: Enable TTY12
  become: yes
  command: systemctl enable getty@tty12.service && systemctl start getty@tty12.service

# - name: Show rsyslog on TTY12
#   become: yes
#   command: echo "daemon,mail.*;\nnews.=crit;news.=err;news.=notice;\n*.=debug;*.=info;\n*.=notice;*.=warn   /dev/tty12" >> /etc/rsyslog.conf

# - name: Restart rsyslog
#   become: yes
#   command: systemctl restart rsyslog