# https://gist.github.com/lbrame/1678c00213c2bd069c0a59f8733e0ee6#forwarding-the-journal-to-devtty12

- name: Have boot messages stay on tty1
  become: yes
  command: echo -e "[Service]\nTTYVTDisallocate=no\n" > /etc/systemd/system/getty@tty1.service.d/noclear.conf

- name: Forwarding the journal to /dev/tty12
  become: yes
  command: echo -e "[Journal]\nForwardToConsole=yesTTYPath=/dev/tty12MaxLevelConsole=info" > /etc/systemd/journald.conf.d/fw-tty12.conf

- name: Restart Systemd Journald Service
  become: yes
  command: systemctl restart systemd-journald.service
