- name: Install Beyond Compare
  yay:
    name:
      - bcompare
    state: present
  become: yes

- name: Copy Beyond Compare config files
  copy:
    src: "{{ ansible_env.PWD }}/roles/bcompare/files"
    dest: "{{ ansible_env.HOME }}/.config/bcompare"
