- name: Install Beyond Compare
  aur:
    name:
      - bcompare

- name: Copy Beyond Compare config files
  copy:
    src: "{{ ansible_env.PWD }}/roles/bcompare/files"
    dest: "{{ ansible_env.HOME }}/.config/bcompare"
