- name: Install package_name_1 and package_name_2 using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - bcompare

- name: Copy Beyond Compare config files
  copy:
    src: "{{ ansible_env.PWD }}/roles/bcompare/files"
    dest: "{{ asnsible_env.HOME }}/.config/bcompare"
