xrdb $HOME/.config/X11/xresources

# This rule is needed when no display manager is used (Removed sddm and use startx instead)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

pgrep -x numlockx > /dev/null || numlockx &
pgrep -x picom > /dev/null || picom &
pgrep -x ntfd > /dev/null || ntfd &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x slstatus > /dev/null || slstatus &

# Start Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


xset -dpms
xset s off # if you also want to disable the screen saver

# https://www.reddit.com/r/bspwm/comments/kf7077/no_cursor_on_startup_appears_when_opening_a/
xsetroot -cursor_name left_ptr

xset +fp $HOME/.local/share/fonts
xset +fp /usr/share/fonts &
fc-cache -fv
xset fp rehash &

# Hide cursor after x time
unclutter -idle 3 &

exec dwm > $HOME/.logs/dwm.log 2>&1
