xrdb $HOME/.config/X11/xresources


# This rule is needed when no display manager is used (Removed sddm and use startx instead)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

pgrep -x numlockx > /dev/null || numlockx &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x ntfd > /dev/null || ntfd &


# Start Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(dbus-launch --sh-syntax --exit-with-session)
eval $(ssh-agent)
export SSH_AUTH_SOCK

# https://www.reddit.com/r/bspwm/comments/kf7077/no_cursor_on_startup_appears_when_opening_a/
xsetroot -cursor_name left_ptr

xset -dpms
xset s off # if you also want to disable the screen saver

# Background color
xsetroot -solid "#3B4252"

systemctl --user start autostart.target

exec bspwm
