- name: Synchronize, Download fresh databases and upgrade all out-of-date packages
  become: yes
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages for a base system
  become: yes
  package:
    name:
      # Base
      - base-devel
      - vim
      - git
      - keychain
      - polkit
      - lxsession-gtk3
      - xorg
      - xorg-xinit
      - network-manager-applet
      - zsh
      - xss-lock
      - xsecurelock
      - jq

      # Theme
      - breeze
      - adwaita-icon-theme
      - papirus-icon-theme

      # Fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra

      # Nice to haves
      - direnv
      - lazygit
      - glab
      - feh
    state: present

- name: Install packages for a virtualization system
  become: yes
  package:
    name:
      - spice-vdagent
    state: present
  when: ansible_virtualization_role == "guest"

- name: Install packages for a non virtualization system
  become: yes
  package:
    name:
      - xf86-video-amdgpu  # Check for amd?
      - xfce4-power-manager  # Check for laptops?
      - numlockx  # Check for numpad?
    state: present
  when: ansible_virtualization_role == "host"

- name: Check if yay exists
  stat:
    path: /usr/bin/yay
  register: check_yay

- name: Install yay (Yet another Yogurt)
  script: "{{ ansible_env.PWD }}/roles/base/scripts/install_yay.sh"
  when: not check_yay.stat.exists

- name: Create the `aur_builder` user
  become: yes
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Install base yay packages
  aur:
    use: yay
    name:
      - ntfd-bin

- name: Install Oh-my-zsh
  become: yes
  script:  "{{ ansible_env.PWD }}/roles/base/scripts/install_oh-my-zsh.sh"
