- name: Install base dependencies
  package:
    name:
      - base-devel
    state: present
  become: yes

- name: Install AUR deploy_helper
  script: "{{ ansible_env.PWD }}/roles/base/files/aur-helper.sh"
