- name: Install base dependencies
  become: yes
  package:
    name:
      - base-devel
      - git
      - lazygit
      - glab
    state: present

- name: Check if yay exists
  stat:
    path: /usr/bin/yay
  register: check_yay

- name: Install yay (Yet another Yogurt)
  script: "{{ ansible_env.PWD }}/roles/base/files/install_yay.sh"
  when: not check_yay.stat.exists

- name: Create the `aur_builder` user
  become: yes
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
