

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.98

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11

[general]
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]
