[_GLOBAL_DEFAULTS]
BalloonTimeout=4000
IconifyFocusLost=true
IconifyMinimized=true
IconifyObscured=true
LockToDesktop=false
SkipPager=false
SkipTaskbar=false
Sticky=false

[obsidian]
AttentionIcon=/usr/share/icons/Papirus-Dark/48x48/apps/obsidian.svg
CustomIcon=/usr/share/icons/Papirus-Dark/48x48/apps/obsidian.svg
IconifyFocusLost=true
IconifyObscured=true
